default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: localhost
  port: 5432

development:
  <<: *default
  database: pushinka_development

test:
  <<: *default
  database: pushinka_test

production:
  <<: *default
  database: pushinka
  username: pushinka
  password: <%= ENV['PUSHINKA_DATABASE_PASSWORD'] %>
