default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  username: <%= ENV['PUSHINKA_DATABASE_USERNAME'] %>
  password: <%= ENV['PUSHINKA_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: pushinka48

test:
  <<: *default
  database: pushinka48

production:
  <<: *default
  database: pushinka48
